const sampleListings = [
  {
    title: "Cozy Cottage",
    desc: "A cozy cottage with a beautiful garden.",
    image: "https://example.com/cottage.jpg",
    price: 120,
    location: "Cottage Lane",
    country: "USA",
  },
  {
    title: "Modern Apartment",
    desc: "A modern apartment in the heart of the city.",
    image: "https://example.com/apartment.jpg",
    price: 200,
    location: "Downtown",
    country: "Canada",
  },
  {
    title: "Beach House",
    desc: "A lovely beach house with stunning sea views.",
    image: "https://example.com/beachhouse.jpg",
    price: 300,
    location: "Ocean Drive",
    country: "Australia",
  },
  {
    title: "Mountain Retreat",
    desc: "A serene retreat in the mountains.",
    image: "",
    price: 150,
    location: "Mountain View",
    country: "Switzerland",
  },
  {
    title: "City Loft",
    desc: "A stylish loft in the city center.",
    image: "https://example.com/loft.jpg",
    price: 250,
    location: "City Center",
    country: "Germany",
  },
  {
    title: "Rural Farmhouse",
    desc: "A spacious farmhouse in the countryside.",
    image: "https://example.com/farmhouse.jpg",
    price: 180,
    location: "Countryside Road",
    country: "France",
  },
  {
    title: "Lakeside Cabin",
    desc: "A cozy cabin by the lake.",
    image: "",
    price: 220,
    location: "Lakeview",
    country: "Canada",
  },
  {
    title: "Penthouse Suite",
    desc: "A luxurious penthouse with city views.",
    image: "https://example.com/penthouse.jpg",
    price: 500,
    location: "High Rise Ave",
    country: "USA",
  },
  {
    title: "Suburban House",
    desc: "A family house in the suburbs.",
    image: "https://example.com/suburban.jpg",
    price: 170,
    location: "Maple Street",
    country: "UK",
  },
  {
    title: "Historic Villa",
    desc: "A historic villa with classic architecture.",
    image: "",
    price: 350,
    location: "Heritage Lane",
    country: "Italy",
  },
  {
    title: "Eco-friendly Home",
    desc: "A sustainable home with modern amenities.",
    image: "https://example.com/ecohome.jpg",
    price: 200,
    location: "Green Street",
    country: "Denmark",
  },
  {
    title: "Urban Flat",
    desc: "A convenient flat in the urban area.",
    image: "https://example.com/flat.jpg",
    price: 140,
    location: "Urban Way",
    country: "Spain",
  },
  {
    title: "Luxury Mansion",
    desc: "An opulent mansion with extensive grounds.",
    image: "https://example.com/mansion.jpg",
    price: 1000,
    location: "Richmond Estate",
    country: "UAE",
  },
  {
    title: "Seaside Bungalow",
    desc: "A charming bungalow by the sea.",
    image: "",
    price: 260,
    location: "Seaside Blvd",
    country: "Portugal",
  },
  {
    title: "Downtown Condo",
    desc: "A modern condo in downtown.",
    image: "https://example.com/condo.jpg",
    price: 300,
    location: "Main Street",
    country: "Japan",
  },
  {
    title: "Country Cottage",
    desc: "A quaint cottage in the countryside.",
    image: "",
    price: 160,
    location: "Country Road",
    country: "Ireland",
  },
  {
    title: "Ski Lodge",
    desc: "A cozy lodge near the ski slopes.",
    image: "https://example.com/skilodge.jpg",
    price: 350,
    location: "Ski Avenue",
    country: "Austria",
  },
  {
    title: "Urban Studio",
    desc: "A small studio in the city.",
    image: "https://example.com/studio.jpg",
    price: 100,
    location: "City Lane",
    country: "Netherlands",
  },
  {
    title: "Countryside Villa",
    desc: "A spacious villa in the countryside.",
    image: "",
    price: 400,
    location: "Villa Road",
    country: "Greece",
  },
  {
    title: "Desert House",
    desc: "A unique house in the desert.",
    image: "https://example.com/deserthouse.jpg",
    price: 280,
    location: "Desert Street",
    country: "Morocco",
  },
];

module.exports = { data: sampleListings };
